version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: devbook_data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devbook
      MYSQL_USER: devbook
      MYSQL_PASSWORD: devbook
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
